manifest:
  remotes:
    - name: nordic
      url-base: https://github.com/nrfconnect
  projects:
    - name: sdk-nrf
      path: nrf
      remote: nordic
      revision: 4c0d3be2ed4ade4dc3e614e95e6f8e4330d663b4
      import: true
  self:
    path: firmware
