manifest:
  remotes:
    - name: nordic
      url-base: https://github.com/nrfconnect
  projects:
    - name: sdk-nrf
      path: nrf
      remote: nordic
      revision: ec780ddc35273b5703e1f97ad2c561557949057e
      import: true
  self:
    path: firmware
